# 侧边栏配置
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post # 页面中高亮的 menu_id
      theme: "#1BCDFC" # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
      icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
      title: 首页 # 标题
      url: / # 跳转链接，支持相对路径和绝对路径
    - id: wiki
      theme: "#3DC550"
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: explore
      theme: "#FA6400"
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/sites/工具库.html
    - id: social
      theme: "#F44336"
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /about/

# 站点主结构树
site_tree:
  # -- 内容类页面 -- #
  # 博客文章内页配置
  home:
    leftbar: welcome, hitokoto, recent
    rightbar: lucky, categories
  post:
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: related, ghrepo, recent # for pages using 'layout:post'
    rightbar: toc, categories
  # 博客专栏文章内页配置
  topic:
    menu_id: post
  # 文档内页配置
  wiki:
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    rightbar: toc
  # 错误页配置
  error_page:
    menu_id: post
    "404": "/404.html"
    leftbar: related, ghrepo, hitokoto, recent
    rightbar: tagcloud, categories
  # 其它自定义页面配置 layout: page
  page:
    leftbar: related, recent
    rightbar: toc, categories, support

open_graph:
  enable: true
  twitter_id: # for open_graph meta

article:
  type: tech # tech/story: story类文字和段落间增距大。
  auto_cover: false # 根据tags在线搜索封面
  auto_excerpt: 100 # 生成摘要的字
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
  license: "本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。" # 许可协议

# 全局样式
style:
  prefers_theme: light
  leftbar:
    background-image: url(https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.13/image/sidebar-bg1@small.jpg)
    blur-px: 100px # 模糊半径
    blur-bg: var(--alpha60) # 模糊颜色
  text-align: left # justify/left/center/right
  darkmode: true # auto true false
  font-size:
    root: 17.5px
    body: 1rem
    code: 80%
    codeblock: 0.8rem
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace'
  color:
    # 动态颜色（会根据明暗主题重设明度值，只用关心色相和饱和度即可）
    background: "hsl(212 16% 98%)" # 浅色背景颜色
    block: "hsl(212 8% 95%)" # 块背景颜色
    code: "hsl(14 100% 48%)" # 行内代码颜色
    text: "hsl(0 0% 20%)" # 文本颜色
    # 主题色配置（不会根据明暗动态调整，请设置为通用的颜色）
    theme: "hsl(192 98% 55%)" # 主题色
    accent: "hsl(14 100% 57%)" # 强调色
    link: "hsl(207 90% 54%)" # 超链接颜色
    button: "hsl(192 98% 55%)" # 按钮颜色
    hover: "hsl(14 100% 57%)" # 按钮高亮颜色
  codeblock:
    highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.min.css
  border-radius:
    card: 12px # 卡片圆角
    block: 12px # 块圆角
    bar: 6px # 导航栏圆角
    image: 6px # 图片圆角

# 页脚
footer:
  social:
    github:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="#000000" d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33s1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2"/></svg>'
      url: https://github.com
    comment:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><g fill="none" stroke="#000000" stroke-linejoin="round"><path stroke-linecap="round" stroke-width="1.5" d="M12 21a9 9 0 1 0-8-4.873L3 21l4.873-1c1.236.639 2.64 1 4.127 1"/><path stroke-width="2.25" d="M7.5 12h.01v.01H7.5zm4.5 0h.01v.01H12zm4.5 0h.01v.01h-.01z"/></g></svg>'
      url: /about/
    rss:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><g fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M4 11a9 9 0 0 1 9 9M4 4a16 16 0 0 1 16 16"/><circle cx="5" cy="19" r="1"/></g></svg>'
      url: /atom.xml
    Moon:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 256 256"><path fill="#000000" d="M233.54 142.23a8 8 0 0 0-8-2a88.08 88.08 0 0 1-109.8-109.8a8 8 0 0 0-10-10a104.84 104.84 0 0 0-52.91 37A104 104 0 0 0 136 224a103.1 103.1 0 0 0 62.52-20.88a104.84 104.84 0 0 0 37-52.91a8 8 0 0 0-1.98-7.98m-44.64 48.11A88 88 0 0 1 65.66 67.11a89 89 0 0 1 31.4-26A106 106 0 0 0 96 56a104.11 104.11 0 0 0 104 104a106 106 0 0 0 14.92-1.06a89 89 0 0 1-26.02 31.4"/></svg>'
      url: javaScript:switchTheme();
    Snow:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="m21 14.25l-.831-.659c-.946-.75-1.419-1.125-1.419-1.591s.473-.841 1.419-1.591L21 9.75m-18 0l.831.659c.946.75 1.419 1.125 1.419 1.591s-.473.841-1.419 1.591L3 14.25M14.572 21l.156-1.059c.178-1.205.267-1.807.674-2.042c.407-.236.972-.011 2.104.437l.994.394M9.428 3l-.156 1.059c-.178 1.205-.267 1.807-.674 2.042c-.407.236-.972.011-2.104-.437L5.5 5.27M5 18.732l1.07-.395c1.218-.448 1.827-.672 2.265-.438s.533.838.724 2.042L9.227 21M19 5.268l-1.07.394c-1.218.45-1.828.673-2.265.439s-.533-.838-.724-2.042L14.773 3M19 12H5m10.5 6l-7-12m7 0l-7 12" color="#000000"/></svg>'
      url: javaScript:toggleSnow();
  sitemap:
    "博客":
      - "[近期](/)"
      - "[分类](/categories/)"
      - "[标签](/tags/)"
      - "[专栏](/topic/)"
      - "[归档](/archives/)"
    "项目":
      - "[牛客刷题](/wiki/niuke/牛客零基础入门前端.html)"
      - "[硅谷甄选](/wiki/ggzx/项目起步.html)"
    "探索":
      - "[站点](/explore/sites/工具库.html)"
      - "[笔记](/explore/notes/探索者笔记.html)"
    "友链":
      - "[朋友圈](/about/)"
  content: | # 支持 Markdown 格式
    <img src="/assets/images/keyboard.jpg" alt="描述文字" style="float: right; width: 60px; margin-left: 20px;">
    <center>
      <div>
        <div>
          © 2024
          <a style="font-weight: bold;  auto;" target="_blank" rel="noopener" href="https://github.com">你的博客名字</a>
          开心地使用 <a style="font-weight: bold;  auto;" target="_blank" rel="noopener" href="https://github.com/xaoxuu/hexo-theme-stellar">Stellar</a>
          主题，星际地球第<span id="runtime_span"></span>
        </div>
        <script type="text/javascript">
          function show_runtime() {
              window.setTimeout("show_runtime()", 1000);
              X = new Date("08/18/2024 00:00:00");
              Y = new Date();
              T = (Y.getTime() - X.getTime());
              M = 24 * 60 * 60 * 1000;
              a = T / M;
              A = Math.floor(a);
              runtime_span.innerHTML = A + "天"
          }
          show_runtime();
        </script>
      </div>
    </center>

copycode:
  enable: false

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)

# 开启图片点击放大功能 {% image %}
tag_plugins:
  image:
    fancybox: true
  icon:
    # 留空时，图标和文字颜色相同
    default_color: accent # theme, accent, red, orange, yellow, green, cyan, blue, purple

# 默认打开
lazyload:
  enable: true # [hexo clean && hexo s] is required after changing this value.
  js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
  transition: blur # blur, fade

# 默认打开
loading:
  loading: 正在加载
  error: 加载失败，请稍后重试。

inject:
  head:
    - <link rel="stylesheet" href="https://npm.elemecdn.com/lxgw-wenkai-screen-webfont/style.css" media="print" onload="this.media='all'">
  script:
    - <script src="https://cdn.jsdelivr.net/gh/huangwb8/bloghelper@latest/js/input-with-fire.js"></script>
    - <script src="https://cdn.staticfile.org/jquery/3.6.3/jquery.min.js"></script> # jQuery
    - <script src="/static/js/snow.js"></script>

